// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EndSession():Promise<void>;

export function GetConfig():Promise<Record<string, string>>;

export function StartSession():Promise<Record<string, string>>;
