// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EndSession() {
  return window['go']['main']['App']['EndSession']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function StartSession() {
  return window['go']['main']['App']['StartSession']();
}
